/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC </br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

db = connect("localhost:27017/Relation_reportingapp");
db.createCollection("users");
db.users.insert([{_id:1,username:"admin",password:"admin",firstname:"admin",lastname:"admin",role:"ROLE_ADMIN"}])
db.users.insert([{_id:2,username:"user",password:"user",firstname:"user",lastname:"user",role:"ROLE_USER"}])
